version: "3.8"

services:
  php:
    build: .
    ports:
      - "85:80"
    volumes:
      - "./app:/var/www/html"
      - "./app/apache:/etc/apache2/sites-available"
    links:
      - database
  database:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=db
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d/
    ports:
      - "3388:3306"
